import { CountryCode } from './types';

export const CountryCodes: Array<CountryCode> = [
  { id: 1, name: 'Afghanistan', dial_code: '+93', code: 'AF' },
  { id: 2, name: 'Aland Islands', dial_code: '+358', code: 'AX' },
  { id: 3, name: 'Albania', dial_code: '+355', code: 'AL' },
  { id: 4, name: 'Algeria', dial_code: '+213', code: 'DZ' },
  { id: 5, name: 'AmericanSamoa', dial_code: '+1 684', code: 'AS' },
  { id: 6, name: 'Andorra', dial_code: '+376', code: 'AD' },
  { id: 7, name: 'Angola', dial_code: '+244', code: 'AO' },
  { id: 8, name: 'Anguilla', dial_code: '+1 264', code: 'AI' },
  { id: 9, name: 'Antarctica', dial_code: '+672', code: 'AQ' },
  { id: 10, name: 'Antigua and Barbuda', dial_code: '+1268', code: 'AG' },
  { id: 11, name: 'Argentina', dial_code: '+54', code: 'AR' },
  { id: 12, name: 'Armenia', dial_code: '+374', code: 'AM' },
  { id: 13, name: 'Aruba', dial_code: '+297', code: 'AW' },
  { id: 14, name: 'Australia', dial_code: '+61', code: 'AU' },
  { id: 15, name: 'Austria', dial_code: '+43', code: 'AT' },
  { id: 16, name: 'Azerbaijan', dial_code: '+994', code: 'AZ' },
  { id: 17, name: 'Bahamas', dial_code: '+1 242', code: 'BS' },
  { id: 18, name: 'Bahrain', dial_code: '+973', code: 'BH' },
  { id: 19, name: 'Bangladesh', dial_code: '+880', code: 'BD' },
  { id: 20, name: 'Barbados', dial_code: '+1 246', code: 'BB' },
  { id: 21, name: 'Belarus', dial_code: '+375', code: 'BY' },
  { id: 22, name: 'Belgium', dial_code: '+32', code: 'BE' },
  { id: 23, name: 'Belize', dial_code: '+501', code: 'BZ' },
  { id: 24, name: 'Benin', dial_code: '+229', code: 'BJ' },
  { id: 25, name: 'Bermuda', dial_code: '+1 441', code: 'BM' },
  { id: 26, name: 'Bhutan', dial_code: '+975', code: 'BT' },
  {
    id: 27,
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    code: 'BO',
  },
  { id: 28, name: 'Bosnia and Herzegovina', dial_code: '+387', code: 'BA' },
  { id: 29, name: 'Botswana', dial_code: '+267', code: 'BW' },
  { id: 30, name: 'Brazil', dial_code: '+55', code: 'BR' },
  {
    id: 31,
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    code: 'IO',
  },
  { id: 32, name: 'Brunei Darussalam', dial_code: '+673', code: 'BN' },
  { id: 33, name: 'Bulgaria', dial_code: '+359', code: 'BG' },
  { id: 34, name: 'Burkina Faso', dial_code: '+226', code: 'BF' },
  { id: 35, name: 'Burundi', dial_code: '+257', code: 'BI' },
  { id: 36, name: 'Cambodia', dial_code: '+855', code: 'KH' },
  { id: 37, name: 'Cameroon', dial_code: '+237', code: 'CM' },
  { id: 38, name: 'Canada', dial_code: '+1', code: 'CA' },
  { id: 39, name: 'Cape Verde', dial_code: '+238', code: 'CV' },
  { id: 40, name: 'Cayman Islands', dial_code: '+ 345', code: 'KY' },
  { id: 41, name: 'Central African Republic', dial_code: '+236', code: 'CF' },
  { id: 42, name: 'Chad', dial_code: '+235', code: 'TD' },
  { id: 43, name: 'Chile', dial_code: '+56', code: 'CL' },
  { id: 44, name: 'China', dial_code: '+86', code: 'CN' },
  { id: 45, name: 'Christmas Island', dial_code: '+61', code: 'CX' },
  { id: 46, name: 'Cocos (Keeling) Islands', dial_code: '+61', code: 'CC' },
  { id: 47, name: 'Colombia', dial_code: '+57', code: 'CO' },
  { id: 48, name: 'Comoros', dial_code: '+269', code: 'KM' },
  { id: 49, name: 'Congo', dial_code: '+242', code: 'CG' },
  {
    id: 50,
    name: 'Congo, The Democratic Republic of the Congo',
    dial_code: '+243',
    code: 'CD',
  },
  { id: 51, name: 'Cook Islands', dial_code: '+682', code: 'CK' },
  { id: 52, name: 'Costa Rica', dial_code: '+506', code: 'CR' },
  { id: 53, name: "Cote d'Ivoire", dial_code: '+225', code: 'CI' },
  { id: 54, name: 'Croatia', dial_code: '+385', code: 'HR' },
  { id: 55, name: 'Cuba', dial_code: '+53', code: 'CU' },
  { id: 56, name: 'Cyprus', dial_code: '+357', code: 'CY' },
  { id: 57, name: 'Czech Republic', dial_code: '+420', code: 'CZ' },
  { id: 58, name: 'Denmark', dial_code: '+45', code: 'DK' },
  { id: 59, name: 'Djibouti', dial_code: '+253', code: 'DJ' },
  { id: 60, name: 'Dominica', dial_code: '+1 767', code: 'DM' },
  { id: 61, name: 'Dominican Republic', dial_code: '+1 849', code: 'DO' },
  { id: 62, name: 'Ecuador', dial_code: '+593', code: 'EC' },
  { id: 63, name: 'Egypt', dial_code: '+20', code: 'EG' },
  { id: 64, name: 'El Salvador', dial_code: '+503', code: 'SV' },
  { id: 65, name: 'Equatorial Guinea', dial_code: '+240', code: 'GQ' },
  { id: 66, name: 'Eritrea', dial_code: '+291', code: 'ER' },
  { id: 67, name: 'Estonia', dial_code: '+372', code: 'EE' },
  { id: 68, name: 'Ethiopia', dial_code: '+251', code: 'ET' },
  {
    id: 69,
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    code: 'FK',
  },
  { id: 70, name: 'Faroe Islands', dial_code: '+298', code: 'FO' },
  { id: 71, name: 'Fiji', dial_code: '+679', code: 'FJ' },
  { id: 72, name: 'Finland', dial_code: '+358', code: 'FI' },
  { id: 73, name: 'France', dial_code: '+33', code: 'FR' },
  { id: 74, name: 'French Guiana', dial_code: '+594', code: 'GF' },
  { id: 75, name: 'French Polynesia', dial_code: '+689', code: 'PF' },
  { id: 76, name: 'Gabon', dial_code: '+241', code: 'GA' },
  { id: 77, name: 'Gambia', dial_code: '+220', code: 'GM' },
  { id: 78, name: 'Georgia', dial_code: '+995', code: 'GE' },
  { id: 79, name: 'Germany', dial_code: '+49', code: 'DE' },
  { id: 80, name: 'Ghana', dial_code: '+233', code: 'GH' },
  { id: 81, name: 'Gibraltar', dial_code: '+350', code: 'GI' },
  { id: 82, name: 'Greece', dial_code: '+30', code: 'GR' },
  { id: 83, name: 'Greenland', dial_code: '+299', code: 'GL' },
  { id: 84, name: 'Grenada', dial_code: '+1 473', code: 'GD' },
  { id: 85, name: 'Guadeloupe', dial_code: '+590', code: 'GP' },
  { id: 86, name: 'Guam', dial_code: '+1 671', code: 'GU' },
  { id: 87, name: 'Guatemala', dial_code: '+502', code: 'GT' },
  { id: 88, name: 'Guernsey', dial_code: '+44', code: 'GG' },
  { id: 89, name: 'Guinea', dial_code: '+224', code: 'GN' },
  { id: 90, name: 'Guinea-Bissau', dial_code: '+245', code: 'GW' },
  { id: 91, name: 'Guyana', dial_code: '+595', code: 'GY' },
  { id: 92, name: 'Haiti', dial_code: '+509', code: 'HT' },
  {
    id: 93,
    name: 'Holy See (Vatican City State)',
    dial_code: '+379',
    code: 'VA',
  },
  { id: 94, name: 'Honduras', dial_code: '+504', code: 'HN' },
  { id: 95, name: 'Hong Kong', dial_code: '+852', code: 'HK' },
  { id: 96, name: 'Hungary', dial_code: '+36', code: 'HU' },
  { id: 97, name: 'Iceland', dial_code: '+354', code: 'IS' },
  { id: 98, name: 'India', dial_code: '+91', code: 'IN' },
  { id: 99, name: 'Indonesia', dial_code: '+62', code: 'ID' },
  {
    id: 100,
    name: 'Iran, Islamic Republic of Persian Gulf',
    dial_code: '+98',
    code: 'IR',
  },
  { id: 101, name: 'Iraq', dial_code: '+964', code: 'IQ' },
  { id: 102, name: 'Ireland', dial_code: '+353', code: 'IE' },
  { id: 103, name: 'Isle of Man', dial_code: '+44', code: 'IM' },
  { id: 104, name: 'Israel', dial_code: '+972', code: 'IL' },
  { id: 105, name: 'Italy', dial_code: '+39', code: 'IT' },
  { id: 106, name: 'Jamaica', dial_code: '+1 876', code: 'JM' },
  { id: 107, name: 'Japan', dial_code: '+81', code: 'JP' },
  { id: 108, name: 'Jersey', dial_code: '+44', code: 'JE' },
  { id: 109, name: 'Jordan', dial_code: '+962', code: 'JO' },
  { id: 110, name: 'Kazakhstan', dial_code: '+7 7', code: 'KZ' },
  { id: 111, name: 'Kenya', dial_code: '+254', code: 'KE' },
  { id: 112, name: 'Kiribati', dial_code: '+686', code: 'KI' },
  {
    id: 113,
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: '+850',
    code: 'KP',
  },
  {
    id: 114,
    name: 'Korea, Republic of South Korea',
    dial_code: '+82',
    code: 'KR',
  },
  { id: 115, name: 'Kuwait', dial_code: '+965', code: 'KW' },
  { id: 116, name: 'Kyrgyzstan', dial_code: '+996', code: 'KG' },
  { id: 117, name: 'Laos', dial_code: '+856', code: 'LA' },
  { id: 118, name: 'Latvia', dial_code: '+371', code: 'LV' },
  { id: 119, name: 'Lebanon', dial_code: '+961', code: 'LB' },
  { id: 120, name: 'Lesotho', dial_code: '+266', code: 'LS' },
  { id: 121, name: 'Liberia', dial_code: '+231', code: 'LR' },
  { id: 122, name: 'Libyan Arab Jamahiriya', dial_code: '+218', code: 'LY' },
  { id: 123, name: 'Liechtenstein', dial_code: '+423', code: 'LI' },
  { id: 124, name: 'Lithuania', dial_code: '+370', code: 'LT' },
  { id: 125, name: 'Luxembourg', dial_code: '+352', code: 'LU' },
  { id: 126, name: 'Macao', dial_code: '+853', code: 'MO' },
  { id: 127, name: 'Macedonia', dial_code: '+389', code: 'MK' },
  { id: 128, name: 'Madagascar', dial_code: '+261', code: 'MG' },
  { id: 129, name: 'Malawi', dial_code: '+265', code: 'MW' },
  { id: 130, name: 'Malaysia', dial_code: '+60', code: 'MY' },
  { id: 131, name: 'Maldives', dial_code: '+960', code: 'MV' },
  { id: 132, name: 'Mali', dial_code: '+223', code: 'ML' },
  { id: 133, name: 'Malta', dial_code: '+356', code: 'MT' },
  { id: 134, name: 'Marshall Islands', dial_code: '+692', code: 'MH' },
  { id: 135, name: 'Martinique', dial_code: '+596', code: 'MQ' },
  { id: 136, name: 'Mauritania', dial_code: '+222', code: 'MR' },
  { id: 137, name: 'Mauritius', dial_code: '+230', code: 'MU' },
  { id: 138, name: 'Mayotte', dial_code: '+262', code: 'YT' },
  { id: 139, name: 'Mexico', dial_code: '+52', code: 'MX' },
  {
    id: 140,
    name: 'Micronesia, Federated States of Micronesia',
    dial_code: '+691',
    code: 'FM',
  },
  { id: 141, name: 'Moldova', dial_code: '+373', code: 'MD' },
  { id: 142, name: 'Monaco', dial_code: '+377', code: 'MC' },
  { id: 143, name: 'Mongolia', dial_code: '+976', code: 'MN' },
  { id: 144, name: 'Montenegro', dial_code: '+382', code: 'ME' },
  { id: 145, name: 'Montserrat', dial_code: '+1664', code: 'MS' },
  { id: 146, name: 'Morocco', dial_code: '+212', code: 'MA' },
  { id: 147, name: 'Mozambique', dial_code: '+258', code: 'MZ' },
  { id: 148, name: 'Myanmar', dial_code: '+95', code: 'MM' },
  { id: 149, name: 'Namibia', dial_code: '+264', code: 'NA' },
  { id: 150, name: 'Nauru', dial_code: '+674', code: 'NR' },
  { id: 151, name: 'Nepal', dial_code: '+977', code: 'NP' },
  { id: 152, name: 'Netherlands', dial_code: '+31', code: 'NL' },
  { id: 153, name: 'Netherlands Antilles', dial_code: '+599', code: 'AN' },
  { id: 154, name: 'New Caledonia', dial_code: '+687', code: 'NC' },
  { id: 155, name: 'New Zealand', dial_code: '+64', code: 'NZ' },
  { id: 156, name: 'Nicaragua', dial_code: '+505', code: 'NI' },
  { id: 157, name: 'Niger', dial_code: '+227', code: 'NE' },
  { id: 158, name: 'Nigeria', dial_code: '+234', code: 'NG' },
  { id: 159, name: 'Niue', dial_code: '+683', code: 'NU' },
  { id: 160, name: 'Norfolk Island', dial_code: '+672', code: 'NF' },
  {
    id: 161,
    name: 'Northern Mariana Islands',
    dial_code: '+1 670',
    code: 'MP',
  },
  { id: 162, name: 'Norway', dial_code: '+47', code: 'NO' },
  { id: 163, name: 'Oman', dial_code: '+968', code: 'OM' },
  { id: 164, name: 'Pakistan', dial_code: '+92', code: 'PK' },
  { id: 165, name: 'Palau', dial_code: '+680', code: 'PW' },
  {
    id: 166,
    name: 'Palestinian Territory, Occupied',
    dial_code: '+970',
    code: 'PS',
  },
  { id: 167, name: 'Panama', dial_code: '+507', code: 'PA' },
  { id: 168, name: 'Papua New Guinea', dial_code: '+675', code: 'PG' },
  { id: 169, name: 'Paraguay', dial_code: '+595', code: 'PY' },
  { id: 170, name: 'Peru', dial_code: '+51', code: 'PE' },
  { id: 180, name: 'Philippines', dial_code: '+63', code: 'PH' },
  { id: 181, name: 'Pitcairn', dial_code: '+872', code: 'PN' },
  { id: 182, name: 'Poland', dial_code: '+48', code: 'PL' },
  { id: 183, name: 'Portugal', dial_code: '+351', code: 'PT' },
  { id: 184, name: 'Puerto Rico', dial_code: '+1 939', code: 'PR' },
  { id: 185, name: 'Qatar', dial_code: '+974', code: 'QA' },
  { id: 186, name: 'Romania', dial_code: '+40', code: 'RO' },
  { id: 187, name: 'Russia', dial_code: '+7', code: 'RU' },
  { id: 188, name: 'Rwanda', dial_code: '+250', code: 'RW' },
  { id: 189, name: 'Reunion', dial_code: '+262', code: 'RE' },
  { id: 190, name: 'Saint Barthelemy', dial_code: '+590', code: 'BL' },
  {
    id: 191,
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dial_code: '+290',
    code: 'SH',
  },
  { id: 192, name: 'Saint Kitts and Nevis', dial_code: '+1 869', code: 'KN' },
  { id: 193, name: 'Saint Lucia', dial_code: '+1 758', code: 'LC' },
  {
    id: 194,
    name: 'Saint Martin',
    dial_code: '+590',
    code: 'MF',
  },
  {
    id: 195,
    name: 'Saint Pierre and Miquelon',
    dial_code: '+508',
    code: 'PM',
  },
  {
    id: 196,
    name: 'Saint Vincent and the Grenadines',
    dial_code: '+1 784',
    code: 'VC',
  },
  {
    id: 197,
    name: 'Samoa',
    dial_code: '+685',
    code: 'WS',
  },
  {
    id: 198,
    name: 'San Marino',
    dial_code: '+378',
    code: 'SM',
  },
  {
    id: 199,
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    code: 'ST',
  },
  {
    id: 200,
    name: 'Saudi Arabia',
    dial_code: '+966',
    code: 'SA',
  },
  {
    id: 201,
    name: 'Senegal',
    dial_code: '+221',
    code: 'SN',
  },
  {
    id: 202,
    name: 'Serbia',
    dial_code: '+381',
    code: 'RS',
  },
  {
    id: 203,
    name: 'Seychelles',
    dial_code: '+248',
    code: 'SC',
  },
  {
    id: 204,
    name: 'Sierra Leone',
    dial_code: '+232',
    code: 'SL',
  },
  {
    id: 205,
    name: 'Singapore',
    dial_code: '+65',
    code: 'SG',
  },
  { id: 206, name: 'Slovakia', dial_code: '+421', code: 'SK' },
  {
    id: 207,
    name: 'Slovenia',
    dial_code: '+386',
    code: 'SI',
  },
  {
    id: 208,
    name: 'Solomon Islands',
    dial_code: '+677',
    code: 'SB',
  },
  { id: 209, name: 'Somalia', dial_code: '+252', code: 'SO' },
  {
    id: 210,
    name: 'South Africa',
    dial_code: '+27',
    code: 'ZA',
  },
  {
    id: 211,
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: '+500',
    code: 'GS',
  },
  {
    id: 212,
    name: 'Spain',
    dial_code: '+34',
    code: 'ES',
  },
  {
    id: 213,
    name: 'Sri Lanka',
    dial_code: '+94',
    code: 'LK',
  },
  {
    id: 214,
    name: 'Sudan',
    dial_code: '+249',
    code: 'SD',
  },
  {
    id: 215,
    name: 'Suriname',
    dial_code: '+597',
    code: 'SR',
  },
  {
    id: 216,
    name: 'Svalbard and Jan Mayen',
    dial_code: '+47',
    code: 'SJ',
  },
  {
    id: 217,
    name: 'Swaziland',
    dial_code: '+268',
    code: 'SZ',
  },
  {
    id: 218,
    name: 'Sweden',
    dial_code: '+46',
    code: 'SE',
  },
  {
    id: 219,
    name: 'Switzerland',
    dial_code: '+41',
    code: 'CH',
  },
  {
    id: 220,
    name: 'Syrian Arab Republic',
    dial_code: '+963',
    code: 'SY',
  },
  {
    id: 221,
    name: 'Taiwan',
    dial_code: '+886',
    code: 'TW',
  },
  { id: 222, name: 'Tajikistan', dial_code: '+992', code: 'TJ' },
  {
    id: 223,
    name: 'Tanzania, United Republic of Tanzania',
    dial_code: '+255',
    code: 'TZ',
  },
  {
    id: 224,
    name: 'Thailand',
    dial_code: '+66',
    code: 'TH',
  },
  {
    id: 225,
    name: 'Timor-Leste',
    dial_code: '+670',
    code: 'TL',
  },
  { id: 226, name: 'Togo', dial_code: '+228', code: 'TG' },
  {
    id: 227,
    name: 'Tokelau',
    dial_code: '+690',
    code: 'TK',
  },
  {
    id: 228,
    name: 'Tonga',
    dial_code: '+676',
    code: 'TO',
  },
  {
    id: 229,
    name: 'Trinidad and Tobago',
    dial_code: '+1 868',
    code: 'TT',
  },
  {
    id: 230,
    name: 'Tunisia',
    dial_code: '+216',
    code: 'TN',
  },
  {
    id: 231,
    name: 'Turkey',
    dial_code: '+90',
    code: 'TR',
  },
  {
    id: 233,
    name: 'Turkmenistan',
    dial_code: '+993',
    code: 'TM',
  },
  {
    id: 234,
    name: 'Turks and Caicos Islands',
    dial_code: '+1 649',
    code: 'TC',
  },
  {
    id: 235,
    name: 'Tuvalu',
    dial_code: '+688',
    code: 'TV',
  },
  {
    id: 236,
    name: 'Uganda',
    dial_code: '+256',
    code: 'UG',
  },
  {
    id: 237,
    name: 'Ukraine',
    dial_code: '+380',
    code: 'UA',
  },
  {
    id: 238,
    name: 'United Arab Emirates',
    dial_code: '+971',
    code: 'AE',
  },
  {
    id: 239,
    name: 'United Kingdom',
    dial_code: '+44',
    code: 'GB',
  },
  {
    id: 240,
    name: 'United States',
    dial_code: '+1',
    code: 'US',
  },
  {
    id: 241,
    name: 'Uruguay',
    dial_code: '+598',
    code: 'UY',
  },
  {
    id: 242,
    name: 'Uzbekistan',
    dial_code: '+998',
    code: 'UZ',
  },
  {
    id: 243,
    name: 'Vanuatu',
    dial_code: '+678',
    code: 'VU',
  },
  {
    id: 244,
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dial_code: '+58',
    code: 'VE',
  },
  {
    id: 245,
    name: 'Vietnam',
    dial_code: '+84',
    code: 'VN',
  },
  {
    id: 246,
    name: 'Virgin Islands, British',
    dial_code: '+1 284',
    code: 'VG',
  },
  {
    id: 247,
    name: 'Virgin Islands, U.S.',
    dial_code: '+1 340',
    code: 'VI',
  },
  {
    id: 248,
    name: 'Wallis and Futuna',
    dial_code: '+681',
    code: 'WF',
  },
  {
    id: 249,
    name: 'Yemen',
    dial_code: '+967',
    code: 'YE',
  },
  {
    id: 250,
    name: 'Zambia',
    dial_code: '+260',
    code: 'ZM',
  },
  {
    id: 251,
    name: 'Zimbabwe',
    dial_code: '+263',
    code: 'ZW',
  },
];
